name: CMake workflow

on:
  push:
    branches: [ "COI-7-python3" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_NAME: Demo

jobs:
  Archon-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependecies
      run: |
        ls -l
        .github/workflows/install-deps.sh
      shell: bash

    - name: Build Demo ACF
      run: |
        cd ${{github.workspace}}/demo
        make ${{env.BUILD_NAME}}
